# Generated by Django 5.2.6 on 2025-12-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='custom/')),
                ('price', models.IntegerField(default=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
